on:
  schedule:
    # Every day at 2:07 UTC: https://crontab.guru/#7_2_*_*_*
    - cron: "7 2 * * *"

jobs:
  fastlane-update:
    # Do not run on forks.
    if: startsWith(github.repository, 'futureware-tech/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Copy over shared workflow overlays.
      - uses: actions/checkout@v2
        with:
          repository: futureware-tech/.github
          # Has to be under the repository directory, otherwise checkout fails.
          path: tmp/.github
      - run: cp -rf tmp/.github/workflows .github/

      # Copy over repository-specific custom overlay.
      - uses: actions/checkout@v2
        with:
          repository: futureware-tech/overlays
          path: tmp/overlays
      - run: |
          if [ -r OVERLAY ]; then
            cp -rf "tmp/overlays/$(<OVERLAY)/." .
          fi

      - run: rm -rf tmp

      - name: "Check for changes and create/update PR"
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.FASTLANE_UPDATE_GITHUB_TOKEN }}"
          commit-message: "[auto] update overlays"
          branch: update-overlays
          title: "[auto] update overlays"
          labels: auto
